### ISSUE TITLE
Replace `lib/data/puppeteer-core` with `puppeteer-core` dependency

### ISSUE THREAD

**Issue by rtritto** [zfcsoftware/puppeteer-real-browser#135]
`lib/data/puppeteer-core` folder has _35.6 MB_ as size and it can be replaced and maintained as `puppeteer-core` dependency

**Comment by zfcsoftware** [comment]
https://github.com/rebrowser/rebrowser-patches
The relevant puppeteer-core file was patched with this update, and Runtime usage was disabled. Since the patch doesn't work correctly on every operating system and version, I wanted to include the pre-patched version directly in the library. When downloaded via npm, it catches most of the issues in the test file.
https://github.com/zfcsoftware/puppeteer-real-browser/blob/ecfcef6946d68b75e0e7d98dc21797a3c016b12c/test/cjs/test.js#L27

**Comment by rtritto** [comment]
You can maybe use a library like [patch-package](https://www.npmjs.com/package/patch-package) where with `"postinstall": "patch-package"` in _scripts_ you can apply all patches

**Comment by zfcsoftware** [comment]
https://www.npmjs.com/package/puppeteer-core-patch
Updated.
