### ISSUE TITLE
Concurrency mode

### ISSUE THREAD

**Issue by artem-a** [zfcsoftware/puppeteer-real-browser#157]
Hi, is it possible to open multiple pages in concurrency mode?

I mean something like that:
```javascript
const { browser } = await connect({}); // one instance

// run this code for every request
const context = await browser.createBrowserContext();
const page = await context.newPage();
await page.goto('https://example.com');
await page.close();
await context.close();

// or
const page = await browser.newPage();
await page.goto('https://example.com');
await page.close();
```
the main goal is one browser instance and open a new page for each request (many concurrent requests) and bypass bot-detection.

**Comment by Tomsonx232** [comment]
Yes you can open multiple pages in a single browser.

I wouldn't recommend opening a new page for each request though, if you are scraping a few hundred links that means a few hundred pages are going to open up all at once which will probably crash your browser due to too much memory being used.

I would take the links you wish to crawl, split them up into 10 smaller lists and then open 10 pages and have each page go through their assigned smaller list.

**Comment by zfcsoftware** [comment]
The library aims to make Puppeteer as undetectable as possible. It applies many patches. createBrowserContext may be blocking some of these patches, or the site may recognize you with a library like fingerprintjs.
https://github.com/fingerprintjs/fingerprintjs
I can't say anything clear about this, but you can try to change the fingerprint with the help of libraries like stealth plugin fe puppeteer-afp.
