### ISSUE TITLE
How to provide a fake user agent and user agent hint headers and remain undetected?

### ISSUE THREAD

**Issue by stickypan** [zfcsoftware/puppeteer-real-browser#190]
### Description

#58 mentions that using  `--user-agent` flag or `page.setUserAgent` might get you detected. Is there any reliable way to provide a user agent without being detected? if not, what is the least detectable way do to that? Some browsers also send additional headers such as  `Sec-CH-UA`, `Sec-CH-UA-Platform` etc. along with the user agent. Is it possible to deal with these additional headers too?

I thought about setting the `--user-agent` flag and then setting the headers manually using `setExtraHTTPHeaders`, but I wonder if that might break the fake fingerprint mechanism that this library uses?

### Full steps to reproduce the issue

No steps

### Issue Type

Support, Documentation Request

### Operating System

Other

### Do you use Docker?

None

**Comment by zfcsoftware** [comment]
Hello, this library does not use fake fingerprint values. I recommend using it with minimal changes, as every change will leave a trace behind.

https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/getHighEntropyValues#examples
![image](https://github.com/user-attachments/assets/b4cbfa65-881a-4563-a99a-9dacffcc1ff8)

When you change the values in the user-agent such as operating system, browser version, browser type, etc., a lot of changes need to be made in the window object. For this reason, this library does not make any changes to the user agent. 
If you need to change fingerprint,
https://github.com/apify/fingerprint-suite
you can change it with this library. However, I recommend you to change only the fingerprint without changing the operating system and browser.

Since there are no plans to change user-agent for this library, I will close it.

**Comment by captainjackrana** [comment]
@zfcsoftware Could you give an example of how to use the fingerprint-suite with `puppeteer-real-browser` ?

`fingerprint-injector` requires a `browser` reference and returns a page, while realbrowser returns a page in itself, which could cause conflicts
