### ISSUE TITLE
Please take care to fill in all fields. Recreating the issue will speed up its resolution. Thank you for contributing to the betterment of the library by reporting issues.

### ISSUE THREAD

**Issue by Ryux05** [zfcsoftware/puppeteer-real-browser#192]
### Description

I am experiencing issues when trying to deploy `puppeteer-real-browser` to Vercel. The deployment fails with compatibility errors that prevent the application from running.

### Full steps to reproduce the issue

1. Create a new project using puppeteer-real-browser.
2. Attempt to deploy the project to Vercel using the Vercel CLI.
3. Observe the error messages during the deployment process.

### Issue Type

Others

### Operating System

Windows 10

### Do you use Docker?

I don't use Docker

**Comment by RubberArchind** [comment]
there are 2 things i want to tell you.
1. please give a good and clear title about your problem next time
2. i dont think this will work in vercel, because you have to install some stuff like xvfb which i am pretty sure vercel doesnt facilitate that, also this is not a "normal" puppeteer, i think you are better off using the docker approach

**Comment by zfcsoftware** [comment]
It will not work with vercel as it needs to work with headless false and has system level dependencies. It can be used on systems with Docker support.
