### ISSUE TITLE
aws lambda

### ISSUE THREAD

**Issue by mishabiletskyi** [zfcsoftware/puppeteer-real-browser#27]
Hi =)
I'll admit right away that I'm a beginner in development
I can't quite figure out if it's possible to use puppeteer-real-browser in aws lambda, or if I'm doing something wrong and I'm getting a lot of errors.

**Comment by zfcsoftware** [comment]
Hello, xvfb cannot be run in services such as aws lamda, cloudflare workers, google functions because it must be installed at system level. It can be run on services with container support like google cloud run. You can turn your project into a docker container using the Dockerfile file in the main directory and use it on google cloud run without any problem.

**Comment by theodorebourgeon** [comment]
Hello, sorry to reopen this topic but you can use a docker container in aws lambda, we are still facing a` Error  during scraping: TypeError: Cannot read properties of undefined (reading 'on')`, is that not working even in a docker environment? Do you have any feedback on that ? 

Thank you so much for the amazing library

**Comment by francosalcedo** [comment]
You could try using a Lambda layer for that.
https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html
https://aws.amazon.com/es/blogs/compute/working-with-lambda-layers-and-extensions-in-container-images/

**Comment by theodorebourgeon** [comment]
@francosalcedo  Not sure adding in layer would help because locally using a lambda dockercontainer it works well, but once deployed its behaviour change
![image](https://github.com/user-attachments/assets/fa168076-926a-46c1-b089-b4e9bb09f970)

**Comment by Jokero** [comment]
@theodorebourgeon were you able to solve the issue with `Cannot read properties of undefined (reading 'on')`?
