### ISSUE TITLE
Linux non headless not working

### ISSUE THREAD

**Issue by 0-don** [zfcsoftware/puppeteer-real-browser#54]
Why doesn't it open the Chrome window on Linux? I saw your preview video, and you did screenshots on interval. Isn't there a better way just for debugging purposes? Afterwards, using headless as normal would be better. 

```ts
import { connect } from "puppeteer-real-browser";

connect({
  headless: false,
  turnstile: true,
})
  .then(async (response) => {
    const { browser, page } = response;

    setInterval(async () => {
      await page.screenshot({ path: "./page.jpg" });
    }, 250);
    await page.goto("https://disboard.org/");
  })
  .catch((error) => {
    console.log(error.message);
  });
```

```sh
[don@arch pup]$ node index.mjs 
[ERROR] [PUPPETEER-REAL-BROWSER] | This library is stable with headless: true in linuxt environment and headless: false in Windows environment. Please send headless: 'auto' for the library to work efficiently.
```

**Comment by zfcsoftware** [comment]
In fact, the browser opens, but you can't see it because it is launched on a virtual screen. Thanks to xvfb, on Linux operating systems we can launch the browser on a virtual screen instead of on our own screen. The library takes advantage of this feature.

https://github.com/zfcsoftware/puppeteer-real-browser/blob/dc173d62c0634e2d273bf6ac35d7afc1e47e1ed8/src/module/chromium.js#L57

If you are talking about the headless feature, it does not work except false. This is because Chrome disables some window properties when new and true. It can be used but not recommended as it will be detected. 

https://stackoverflow.com/questions/68289474/selenium-headless-how-to-bypass-cloudflare-detection-using-selenium

**Comment by 0-don** [comment]
Thanks for the explanation about Xvfb. It seems to work with `headless: false` on Windows, showing the screen. I know this increases detection risk, but it would be nice to have an option to toggle Xvfb for debugging on other pages in linux.
